export type Song = {
  id: number;
  name: string;
  youtubeId: string;
  tags: string[];
  artists: string[];
  featured: boolean;
  date: Date;
  productionDetails: {
    VideoStudio?: string;
    RecordingStudio?: string;
    BeatFrom?: string;
  };
};

export const songs: Song[] = [
  {
    id: 1,
    name: "Belong Together",
    artists: ["LeoTheProdu", "Fátima Pinto"],
    tags: ["Pop", "Remix", "EDM Trap"],
    date: new Date("2017-08-24"),
    featured: false,
    productionDetails: {
      BeatFrom: "FLProd.",
    },
    youtubeId: "kUDCr5UTBoU",
  },
  {
    id: 2,
    name: "Epicopile",
    artists: ["Edriel"],
    tags: ["Dembow", "Reggaeton", "Cumbia"],
    date: new Date("2022-11-01"),
    featured: false,
    productionDetails: {
      BeatFrom: "FLProd.",
      VideoStudio: "Edriel",
      RecordingStudio: "FLProd.",
    },
    youtubeId: "-3IR-HfOqLo",
  },
  {
    id: 3,
    name: "Jump🍑Up🆙",
    artists: ["TH1"],
    tags: ["Afrobeat"],
    date: new Date("2023-07-23"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "vJ6TX5kkk3U",
  },
  {
    id: 4,
    name: "Sirenas",
    artists: ["La Rana Roja"],
    tags: ["Rock"],
    date: new Date("2024-09-12"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "kCDYp6FuWgk",
  },
  {
    id: 5,
    name: "En La Oscuridad (Londres 1888)",
    artists: ["La Rana Roja"],
    tags: ["Rock"],
    date: new Date("2024-02-06"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "2cU3JpkVR5Y",
  },
  {
    id: 6,
    name: "Baila Pa Mi",
    artists: ["D-Again"],
    tags: ["Afrobeat"],
    date: new Date("2023-12-21"),
    featured: false,
    productionDetails: {
      BeatFrom: "Ackee Beats",
      RecordingStudio: "FLProd.",
    },
    youtubeId: "SnZNVXcYRXg",
  },
  {
    id: 7,
    name: "Bendecidos",
    artists: ["Cesar JS", "D-Again"],
    tags: ["DanceHall"],
    date: new Date("2023-11-29"),
    featured: false,
    productionDetails: {
      BeatFrom: "DJ Otoya",
      RecordingStudio: "FLProd.",
      VideoStudio: "D-Again",
    },
    youtubeId: "bmaDpQ-5eF8",
  },
  {
    id: 8,
    name: "Caribbean Paradise",
    artists: ["César Js", "Andrey Gonzáles", "Davis", "Zophie"],
    tags: ["Afrobeat"],
    date: new Date("2023-09-29"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      VideoStudio: "Chritian Arri",
      BeatFrom: "FLProd.",
    },
    youtubeId: "t3rxM8PPm5Q",
  },
  {
    id: 9,
    name: "Ángeles Caídas",
    artists: ["FRANKOXXX"],
    tags: ["HipHop"],
    date: new Date("2023-09-22"),
    featured: false,
    productionDetails: {},
    youtubeId: "yvuBpVl01Y0",
  },
  {
    id: 10,
    name: "Don't Stop",
    artists: ["V-Shon"],
    tags: ["Reggae", "Positive"],
    date: new Date("2023-08-16"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "6Og0qnTUSIU",
  },
  {
    id: 11,
    name: "Busqueda Infinita",
    artists: ["La Rana Roja"],
    tags: ["Rock"],
    date: new Date("2023-08-05"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "72EV9GRB3Eo",
  },
  {
    id: 12,
    name: "Art Attack",
    artists: ["FRANKOXXX"],
    tags: ["HipHop"],
    date: new Date("2023-05-19"),
    featured: false,
    productionDetails: {},
    youtubeId: "zwUaiwfiyVw",
  },
  {
    id: 13,
    name: "Solita",
    artists: ["Fauricio Cruz"],
    tags: ["Reggaeton"],
    date: new Date("2023-05-05"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "Kachorro's Films",
    },
    youtubeId: "2887f7Oy74Y",
  },
  {
    id: 14,
    name: "Llorando",
    artists: ["Fauricio Cruz"],
    tags: ["Reggaeton"],
    date: new Date("2023-03-16"),
    featured: false,
    productionDetails: {},
    youtubeId: "1Ucf-egmgC4",
  },
  {
    id: 15,
    name: "Until We Meet Again",
    artists: ["La Rana Roja"],
    tags: ["Rock"],
    date: new Date("2022-10-11"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "1_2rLpumueo",
  },
  {
    id: 16,
    name: "Adicto",
    artists: ["Fauricio Cruz"],
    tags: ["Rap"],
    date: new Date("2022-10-07"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
    },
    youtubeId: "J-tlj_G-n7E",
  },
  {
    id: 17,
    name: "Hola Mamá",
    artists: ["Fauricio Cruz"],
    tags: ["DanceHall"],
    date: new Date("2022-10-07"),
    featured: false,
    productionDetails: {
      BeatFrom: "FLProd.",
      RecordingStudio: "FLProd.",
    },
    youtubeId: "AjGLEN6PlR8",
  },
  {
    id: 18,
    name: "Pobre Corazón",
    artists: ["Fauricio Cruz"],
    tags: ["Reggaeton"],
    date: new Date("2022-09-29"),
    featured: false,
    productionDetails: {
      BeatFrom: "FLProd.",
      RecordingStudio: "FLProd.",
      VideoStudio: "Ebbydangmusic",
    },
    youtubeId: "Gj9n4OgWcrM",
  },
  {
    id: 19,
    name: "Llega el Amor",
    artists: ["Fauricio Cruz"],
    tags: ["Bachata"],
    date: new Date("2022-09-07"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
    },
    youtubeId: "npwmnYrKuLQ",
  },
  {
    id: 20,
    name: "süs",
    artists: ["FRANKOXXX", "Lezs"],
    tags: ["HipHop"],
    date: new Date("2022-04-22"),
    featured: false,
    productionDetails: {},
    youtubeId: "nDfKjWMLJpU",
  },
  {
    id: 21,
    name: "Even in the Rain",
    artists: ["La Rana Roja"],
    tags: ["Rock"],
    date: new Date("2021-03-12"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "8uMV8n13_ec",
  },
  {
    id: 22,
    name: "Noches Sin Viento",
    artists: ["La Rana Roja"],
    tags: ["Rock"],
    date: new Date("2020-11-07"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "zXSBaqLcYcc",
  },
  {
    id: 23,
    name: "Somos Los Que Somos",
    artists: ["La Rana Roja"],
    tags: ["Rock"],
    date: new Date("2020-08-22"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "2HgWOGFsZdk",
  },
  {
    id: 24,
    name: "Traicionera",
    artists: ["TH1"],
    tags: ["Dancehall"],
    date: new Date("2015-06-01"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "M0oru0276wE",
  },
  {
    id: 25,
    name: "Quisiera",
    artists: ["Cesar JS"],
    tags: ["Reggae", "Positivo"],
    date: new Date("2025-05-16"),
    featured: true,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
    },
    youtubeId: "edZhTp0-lvI",
  },
  {
    id: 26,
    name: "818",
    artists: ["KGM"],
    tags: ["Reggaeton"],
    date: new Date("2025-05-14"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "FLProd.",
    },
    youtubeId: "HM0PIkyx6_s",
  },
  {
    id: 27,
    name: "Buenos Amigos",
    artists: ["Williams"],
    tags: ["DanceHall"],
    date: new Date("2024-10-15"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "pT7QzVevaTE",
  },
  {
    id: 28,
    name: "Como Aquella Noche",
    artists: ["Williams"],
    tags: ["DanceHall"],
    date: new Date("2024-12-18"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      VideoStudio: "FLProd.",
    },
    youtubeId: "pkLP7zdNBdI",
  },
  {
    id: 29,
    name: "Ahora me llama",
    artists: ["Yerking", "Joztin Bwoy", "Jafet", "Reilo"],
    tags: ["DanceHall"],
    date: new Date("2022-03-23"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      VideoStudio: "Kachorro's Films",
    },
    youtubeId: "pkLP7zdNBdI",
  },
  {
    id: 30,
    name: "Kuchy Kuchy",
    artists: ["El Daddy"],
    tags: ["DanceHall"],
    date: new Date("2021-12-24"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      VideoStudio: "Kachorro's Films",
    },
    youtubeId: "BPm5k6x-UH8",
  },
  {
    id: 31,
    name: "Angel",
    artists: ["Cesar JS", "Zophie"],
    tags: ["Hip Hop"],
    date: new Date("2024-12-04"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "Studio Savage",
    },
    youtubeId: "puMaYh084MM",
  },
  {
    id: 32,
    name: "Quisiera",
    artists: ["Beto G"],
    tags: ["DanceHall", "Romántico"],
    date: new Date("2022-04-16"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "Kachorro's Films",
    },
    youtubeId: "0P3x9xGBhRQ",
  },
  {
    id: 33,
    name: "Tiempos de antes",
    artists: ["Beto G"],
    tags: ["Reggae", "Romantic Style"],
    date: new Date("2023-02-08"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "Kachorro's Films",
    },
    youtubeId: "un3UkYuS2T4",
  },
  {
    id: 34,
    name: "María",
    artists: ["Beto G"],
    tags: ["Reggae", "Romantic Style"],
    date: new Date("2021-10-20"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "Kachorro's Films",
    },
    youtubeId: "TOzuhihC4q8",
  },
  {
    id: 35,
    name: "Porqué",
    artists: ["Beto G"],
    tags: ["Reggae", "Romantic Style"],
    date: new Date("2020-12-03"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "Kachorro's Films",
    },
    youtubeId: "xBjfcxZgcmY",
  },
  {
    id: 36,
    name: "A donde vas",
    artists: ["KMG"],
    tags: ["Reggaeton"],
    date: new Date("2022-10-18"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "Kachorro's Films",
    },
    youtubeId: "0eDlErSQwRI",
  },
  {
    id: 37,
    name: "Apocalipsis",
    artists: ["KMG"],
    tags: ["Trap"],
    date: new Date("2024-04-18"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "Kachorro's Films",
    },
    youtubeId: "NApnEBSDKJA",
  },
  {
    id: 38,
    name: "Promesas",
    artists: ["Jafet", "Yerking", "Reilo"],
    tags: ["Dancehall", "Romántico"],
    date: new Date("2025-05-02"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      VideoStudio: "FLProd.",
    },
    youtubeId: "ib-6nUQZ3po",
  },
  {
    id: 39,
    name: "20 kilómetros",
    artists: ["Rousses"],
    tags: ["Reggaeton", "Romántico"],
    date: new Date("2023-01-26"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "FLProd.",
    },
    youtubeId: "-pxtDkUtwoY",
  },
  {
    id: 40,
    name: "Antónimo de buena",
    artists: ["Rousses"],
    tags: ["Reggaeton", "Party"],
    date: new Date("2020-03-17"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
    },
    youtubeId: "h7ZjJTkcGSc",
  },
  {
    id: 41,
    name: "Alas Rotas",
    artists: ["Rousses", "Colle M"],
    tags: ["Hip Hop"],
    date: new Date("2019-10-29"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
    },
    youtubeId: "QijgL4rJjI0",
  },
  {
    id: 42,
    name: "Sosten mi mano",
    artists: ["Rousses"],
    tags: ["Hip Hop"],
    date: new Date("2019-02-03"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "FLProd.",
    },
    youtubeId: "7DmXEoIEnjM",
  },
  {
    id: 43,
    name: "Yo Quiero",
    artists: ["Rousses", "Guzza's", "D-Crown"],
    tags: ["Hip Hop", "Trap"],
    date: new Date("2018-11-12"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "FLProd.",
    },
    youtubeId: "XHQJpAk-kHk",
  },
  {
    id: 44,
    name: "Badmind",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Tico Showtime"],
    date: new Date("2025-03-26"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "Killa prod.",
      VideoStudio: "Studio Savage",
    },
    youtubeId: "Fp1h8lpiWtE",
  },
  {
    id: 45,
    name: "Ten cuidado",
    artists: ["Cesar Js"],
    tags: ["Trap", "M.O.T.M"],
    date: new Date("2025-04-30"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
    },
    youtubeId: "SiTiH4FRC18",
  },
  {
    id: 46,
    name: "Leyenda",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Folk Showtime", "Freestyle"],
    date: new Date("2024-12-25"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "VflQKUQQ4G4",
  },
  {
    id: 47,
    name: "Hustler",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Bamboo Studios"],
    date: new Date("2024-12-25"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "Studio Savage",
    },
    youtubeId: "5A2YG59BFU0",
  },
  {
    id: 48,
    name: "Malicia",
    artists: ["Cesar Js"],
    tags: ["Dancehall"],
    date: new Date("2024-06-21"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "David Varji",
    },
    youtubeId: "SdXXlG0-F38",
  },
  {
    id: 49,
    name: "Amenaza",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Stainless", "DJ Karim"],
    date: new Date("2024-05-03"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "",
    },
    youtubeId: "22Alpxz_ysw",
  },
  {
    id: 50,
    name: "Nah fallow",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Street Vybz"],
    date: new Date("2024-02-09"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "",
      VideoStudio: "",
    },
    youtubeId: "Qh8aeOzokUU",
  },
  {
    id: 51,
    name: "Emociones",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Cover", "Tasted"],
    date: new Date("2024-01-05"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "FLProd.",
      VideoStudio: "",
    },
    youtubeId: "0dIL6LDkwto",
  },
  {
    id: 52,
    name: "Intro",
    artists: ["Cesar Js", "DJ Juan"],
    tags: ["Dancehall", "Nos Fuimos Retro"],
    date: new Date("2023-12-15"),
    featured: false,
    productionDetails: {
      RecordingStudio: "",
      BeatFrom: "",
      VideoStudio: "",
    },
    youtubeId: "HRAAfgeuXtQ",
  },
  {
    id: 53,
    name: "Franquicia",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Nos Fuimos Retro", "LeoTheProdu", "DJ Juan"],
    date: new Date("2023-12-15"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "",
    },
    youtubeId: "d63QMCDhXAA",
  },
  {
    id: 54,
    name: "We Up",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Nos Fuimos Retro", "DJ Juan"],
    date: new Date("2023-12-15"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "",
    },
    youtubeId: "9zuPAjZDJ8Q",
  },
  {
    id: 55,
    name: "BackShot",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Nos Fuimos Retro", "DJ Juan"],
    date: new Date("2023-12-15"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "",
    },
    youtubeId: "k8fF6mTwgRw",
  },
  {
    id: 56,
    name: "Tu Bandera",
    artists: ["Cesar Js", "Zophie"],
    tags: ["Dancehall", "Nos Fuimos Retro", "DJ Juan"],
    date: new Date("2023-12-15"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "",
    },
    youtubeId: "c_YT2qdAVS0",
  },
  {
    id: 57,
    name: "La Vara",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Nos Fuimos Retro", "DJ Juan"],
    date: new Date("2023-12-15"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "",
    },
    youtubeId: "XVRk9BSTqK0",
  },
  {
    id: 58,
    name: "Budum",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Nos Fuimos Retro", "DJ Juan"],
    date: new Date("2023-12-15"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "",
    },
    youtubeId: "JQmo_pdsnsQ",
  },
  {
    id: 59,
    name: "Bubble",
    artists: ["Cesar Js"],
    tags: ["Dancehall"],
    date: new Date("2023-11-12"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "",
    },
    youtubeId: "9yinMAiEnkE",
  },
  {
    id: 60,
    name: "Cash",
    artists: ["Cesar Js"],
    tags: ["Dancehall"],
    date: new Date("2023-11-08"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "BSMNT",
      VideoStudio: "Breddas Music",
    },
    youtubeId: "A-Lq0pvkYWI",
  },
  {
    id: 61,
    name: "Dancehall Never Die",
    artists: ["Cesar Js"],
    tags: ["Dancehall"],
    date: new Date("2023-10-23"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "Breddas Music",
    },
    youtubeId: "A-Lq0pvkYWI",
  },
  {
    id: 62,
    name: "Welcome to the Jungle",
    artists: ["Cesar Js"],
    tags: ["Dancehall", "Bamboo Studios"],
    date: new Date("2023-10-22"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "Breddas Music",
    },
    youtubeId: "z4Wy-V_JV84",
  },
  {
    id: 63,
    name: "Lengua Larga",
    artists: ["Gran George"],
    tags: ["Hip Hop"],
    date: new Date("2025-03-05"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "",
      VideoStudio: "",
    },
    youtubeId: "qgukSdCG5rQ",
  },
  {
    id: 64,
    name: "Extrañandote",
    artists: ["Gran George"],
    tags: ["Hip Hop"],
    date: new Date("2024-12-10"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "",
      VideoStudio: "",
    },
    youtubeId: "XYg4xCRUJqU",
  },
  {
    id: 65,
    name: "En Lo mío",
    artists: ["Gran George"],
    tags: ["Hip Hop"],
    date: new Date("2024-07-24"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "",
      VideoStudio: "",
    },
    youtubeId: "0N6RrMIYm3Q",
  },
  {
    id: 66,
    name: "Actitudes",
    artists: ["Gran George"],
    tags: ["Hip Hop"],
    date: new Date("2024-05-27"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "",
      VideoStudio: "",
    },
    youtubeId: "MUORlImCVGQ",
  },
  {
    id: 67,
    name: "Mantenme firme",
    artists: ["Gran George"],
    tags: ["Hip Hop"],
    date: new Date("2024-05-15"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "",
      VideoStudio: "",
    },
    youtubeId: "5vmg3TfWT2M",
  },
  {
    id: 68,
    name: "Sé perder",
    artists: ["Gran George"],
    tags: ["Hip Hop"],
    date: new Date("2024-02-02"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "",
      VideoStudio: "",
    },
    youtubeId: "DyihCCkAtXo",
  },
  {
    id: 69,
    name: "Nadie Sabe",
    artists: ["Gran George"],
    tags: ["Hip Hop"],
    date: new Date("2023-06-27"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "",
      VideoStudio: "",
    },
    youtubeId: "bulISmhzwp8",
  },
  {
    id: 70,
    name: "Nadie Sabe",
    artists: ["Myztah Gonzo","Cesar JS", "Charly Bless", "Mista Elegance", "Mr Ken"],
    tags: ["Dancehall", "FLProd.", "Gecko Music", "Fire Links", "CB Producciones"],
    date: new Date("2025-05-23"),
    featured: false,
    productionDetails: {
      RecordingStudio: "Varios",
      BeatFrom: "Piña Beats",
      VideoStudio: "CB Producciones",
    },
    youtubeId: "7-SghTM8Y6Y",
  },
  {
    id: 71,
    name: "No dejo de pensarte",
    artists: ["Williams"],
    tags: ["Afrobeat"],
    date: new Date("2025-06-02"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
    },
    youtubeId: "cdf1uAHT62U",
  },
  {
    id: 72,
    name: "Ten Cuidado",
    artists: ["Cesar Js"],
    tags: ["Trap", "Dancehall"],
    date: new Date("2025-06-11"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      BeatFrom: "DJ Otoya",
      VideoStudio: "Studio Savage",
    },
    youtubeId: "_3fOXsCijvI",
  },
  {
    id: 73,
    name: "My Love",
    artists: ["Williams"],
    tags: ["Dancehall", "Romantic"],
    date: new Date("2025-06-24"),
    featured: false,
    productionDetails: {
      RecordingStudio: "FLProd.",
      VideoStudio: "FLProd."
    },
    youtubeId: "2PXiT6hvNzw",
  },
];
